### ISSUE TITLE
No functions or files have been obfuscated.

### ISSUE THREAD

**Issue by zxc7528064** [cwolff411/powerob#5]
←[0;31m[-] No functions or files have been obfuscated.←[0m

![圖片](https://user-images.githubusercontent.com/45315211/189018162-30211dca-02b3-4086-a141-bb93578fc39e.png)

**Comment by cwolff411** [comment]
This is the command used to show all of your previously obfuscated files along with the corresponding obfuscated functions. If you have not obfuscated any files using the obfuscate command, then nothing will show up here.

**Comment by zxc7528064** [comment]
Hi , why don't find function ?!

![image](https://user-images.githubusercontent.com/45315211/189173008-1b597e14-ca27-49ba-bb29-6c4f335bd9ea.png)
